// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFyqp86k3MruLJB1ZRRUdq-5Mzl2UpwiM',
    appId: '1:804376043146:web:31bdefb38c4908c2355773',
    messagingSenderId: '804376043146',
    projectId: 'mypharmacyassistant-3203f',
    authDomain: 'mypharmacyassistant-3203f.firebaseapp.com',
    storageBucket: 'mypharmacyassistant-3203f.firebasestorage.app',
    measurementId: 'G-RF51D5YY57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTonPRZwBCllAGXtCu92fQH39ey_670Vs',
    appId: '1:804376043146:android:caa8f054f9b93202355773',
    messagingSenderId: '804376043146',
    projectId: 'mypharmacyassistant-3203f',
    storageBucket: 'mypharmacyassistant-3203f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnTj0pNC0fuMK5MfgxPzpyXoaCgfcnv2o',
    appId: '1:804376043146:ios:bc76226348d8f000355773',
    messagingSenderId: '804376043146',
    projectId: 'mypharmacyassistant-3203f',
    storageBucket: 'mypharmacyassistant-3203f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnTj0pNC0fuMK5MfgxPzpyXoaCgfcnv2o',
    appId: '1:804376043146:ios:bc76226348d8f000355773',
    messagingSenderId: '804376043146',
    projectId: 'mypharmacyassistant-3203f',
    storageBucket: 'mypharmacyassistant-3203f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFyqp86k3MruLJB1ZRRUdq-5Mzl2UpwiM',
    appId: '1:804376043146:web:31bdefb38c4908c2355773',
    messagingSenderId: '804376043146',
    projectId: 'mypharmacyassistant-3203f',
    authDomain: 'mypharmacyassistant-3203f.firebaseapp.com',
    storageBucket: 'mypharmacyassistant-3203f.firebasestorage.app',
    measurementId: 'G-RF51D5YY57',
  );
}
